### ISSUE TITLE
[Suggest] LICENSE file name

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#10]
GitHub automatically parses a license file from a root repository into its project dashboard like "Apache2.0", "BSD-3.0" and etc., if and only if that file has the name of "LICENSE". Currently we have the file under the name of "LICENSE.Apache-2.0". 

I would like to suggest to change the current license file name from "LICENSE.Apache-2.0" to "LICENSE". Does it make sense to all?

**Comment by jyong2kim** [comment]
@MoonkiHong 
Thanks for your kindly suggestion.
I agree with you and your suggestion will be applied with following PR.
[PR link](https://github.com/lf-edge/edge-home-orchestration-go/pull/11)

**Comment by MoonkiHong** [comment]
Thank you!!! @jyong2kim
