### ISSUE TITLE
RTT value initialization during device discovery

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#100]
**Describe the bug**
The discoverymgr runs the deviceDetectionRoutine function to find devices at regular intervals.
During this period, it sets the RTT value to 0 even if the corresponding data is in the networkdb.

**Expected behavior**
If the networkdb doesn’t have corresponding data, the networkdb should insert or update the network information. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5847128/86186729-c1c90a80-bb74-11ea-8ee3-3d810bca39a5.png)

**Test environment configuration (please complete the following information):**
* Firmware version: Ubuntu 16.04
* Hardware: x86-64
* Edge Orchestration Release: Baobab

**Comment by MoonkiHong** [comment]
@t25kim Thank you for this report! It definitely is a bug and should be fixed. Could you propose the solution for this reported bug? :D
