### ISSUE TITLE
Use signals instead of timer

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#107]
How about changing [time.sleep functions](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/GoMain/src/main/main.go#L169) to the code controlled by signal such as SIGINT, SIGTERM?
I think it could expand other scenarios such as 
 - A node sends it's termination request to other neighbors if the node receives SIGTERM.

**Comment by MoonkiHong** [comment]
@t25kim Your proposal seems valid, and I have considered that we need to do something. Currently, `watcher` from `configuremgr` might be the similar candidate to provide it, but it seems to me that it is for the service notification on top of edge orchestrator, and we need a separate manager to fully control those termination request handling in conjunction with SIGTERM.

@suresh-lc What do you think of this suggestion?
