### ISSUE TITLE
Build source code to x86_64 on RPi 

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#119]
**Describe the bug**
The RPi architecture is arm but it builds the source code with x86_64.

**To Reproduce**
1. Download source code on RPi 
2. Build source code like below
  $ ./build

**Screenshots**
```
pi@raspberrypi:~/workspace/edge-home-orchestration-go $ uname -m
armv7l
pi@raspberrypi:~/workspace/edge-home-orchestration-go $ docker logs edge-orchestration
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Test environment configuration (please complete the following information):**
* Hardware: RPi2
* Edge Orchestration Release: Baobab

**Comment by MoonkiHong** [comment]
@t25kim Thank you for the kind report!
