### ISSUE TITLE
[Suggest] Go Report Card representation

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#13]
Since this project has been written in GoLang, I would like to suggest to add the representation banner for "Go Report Card" from the "README.md", which is a famous index to most of the GoLang developers.

- Go Report Card : Open Source for providing index about the GoLang project S/W quality
  (https://goreportcard.com/about/)

Just for your information, Home Edge project is currently evaluated as "A+" from the "Go Report" (reference to : https://goreportcard.com/report/github.com/lf-edge/edge-home-orchestration-go), which is a very encouraging information to the project.

You can check out how we are able to add such a index from the README.md with respect to the document from other project in LF Edge such as Project EVE and EdgeX Foundry. Here is an example.

```
[![CircleCI](https://circleci.com/gh/lf-edge/eve.svg?style=svg)](https://circleci.com/gh/lf-edge/eve)
[![Goreport](https://goreportcard.com/badge/github.com/lf-edge/eve)](https://goreportcard.com/report/github.com/lf-edge/eve)
[![Godoc](https://godoc.org/github.com/lf-edge/eve/pkg/pillar?status.svg)](https://godoc.org/github.com/lf-edge/eve/pkg/pillar)
```

**Comment by jyong2kim** [comment]
@MoonkiHong 
Thanks for your kindly suggestion.
I and @wansuyoo will add report cards.

**Comment by MoonkiHong** [comment]
@jyong2kim @wansuyoo @mgjeong 
We have just sent the pull request for closing this suggestion. Please check it out and let me know shortly if there is any issue. (https://github.com/lf-edge/edge-home-orchestration-go/pull/27)

**Comment by MoonkiHong** [comment]
PR approved. Thank you.
