### ISSUE TITLE
Modify the `binPath` for elasticity

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#136]
_Originally posted by @t25kim in https://github.com/lf-edge/edge-home-orchestration-go/pull/135#discussion_r499484193_

![image](https://user-images.githubusercontent.com/5893365/95146531-03db9b00-07b9-11eb-900c-1b11c4a9a50b.png)

What do you think of using edgeDir as below?
```suggestion
	binPath                = edgeDir + "/bin"
```
If this is more reasonable, the YamlFileName and the ConfigFileName are should be changed as well.

**Comment by t25kim** [comment]
Solved

**Comment by MoonkiHong** [comment]
Thank you @t25kim ^^
