### ISSUE TITLE
Role based Access Control (security feature)

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#147]
**Is your feature request related to a problem? Please describe.**
it is necessary to impose restrictions on access to resources for different users

**Describe the solution you'd like**
It would be great to implement the Role based Access Control

**Comment by MoonkiHong** [comment]
_Suggested by @tdrozdovsky : Email communication with @MoonkiHong_
------
Dear Mr. Peter Moonki Hong,

 

Thank you I'm fine. I hope you are also doing well!

Yesterday we had a day off, so I didn't immediately answer you.


Regarding RBAC, I will prepare the initial version and make a PR. Step by step we will improve it and others security features.

You could watch a video about docker and Edge-Orchestration on Android. If you have any thoughts about it, please, write to me!

-------------
Dear Taras,

 

How have you been there? It is great to hear that you made another great achievement in security enhancement for our project. I really appreciate for your passionate work. Overall, your approach seems good to me. Currently, Suresh, Taewan and I are the key players in Home Edge and we are lookiing forward to your contributions! 

------------
Dear Mr. Moonki Hong,

 

Until that time, I was researching the RBAC (Role-based Access Control), and at the moment I have implemented the initial version of RBAC for Edge-Orchestration and I am doing testing. So soon I will make a PR to inject the RBAC into Edge-Orchestration in secure mode.

Also at my leisure I tried to run docker on the phone, this attempt was successful and after that I tried to run our orchestration system on the phone using the docker container platform. It works very slowly, but it works!))). You can see the video in the attachment.

If you have any questions, write to me, I will be happy to answer them
