### ISSUE TITLE
Secure Mode Judgement

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#149]
**Is your feature request related to a problem? Please describe.**
The Edge Orchestration runs on the secure mode when it's built with "BUILD_TAGS='secure'"

**Describe alternatives you've considered**
How about deciding the secure mode if all the necessary files are in the edgeDir subpath?
 - example of necessary files : orchestration_userID.txt, passPhraseJWT.txt, app_rsa.pub etc

**Comment by MoonkiHong** [comment]
@tdrozdovsky Please take a look at this.

**Comment by tdrozdovsky** [comment]
I'm not sure if I understood the question correctly, but after looking at the comments, I think that they meant that all files must be manually installed by the user for `secure` mode.

I have given answers in the comments to PR #147.

**Comment by MoonkiHong** [comment]
Thank you all for the great opinions. I have left my comment and suggestion to PR #148 (https://github.com/lf-edge/edge-home-orchestration-go/pull/148#issuecomment-712639447).
