### ISSUE TITLE
Build break due to golang version on RPi

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#156]
**Describe the bug**
[RPi instruction](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/doc/platforms/raspberry_pi3/raspberry_pi3.md#2-build-directly-on-the-raspberry-pi-3-board) guides developers to install golang with command `sudo apt install golang`.
RPi install 1.11 version of golang and it fails to build the project.
Find the log below.
```
pi@raspberrypi:~/edge-home-orchestration-go $ go version
go version go1.11.6 linux/arm
pi@raspberrypi:~/edge-home-orchestration-go $ ./build.sh

-----------------------------------
 Install prerequisite packages
-----------------------------------
(1/7) go get -u github.com/axw/gocov/gocov: Done
(2/7) go get -u github.com/matm/gocov-html: Done
(3/7) go get -u golang.org/x/lint/golint: Done
(4/7) go get -u github.com/Songmu/make2help/cmd/make2help: Done
(5/7) go get -u golang.org/x/mobile/cmd/gomobile# golang.org/x/tools/go/packages
../go/src/golang.org/x/tools/go/packages/golist_overlay.go:547:7: undefined: strings.ReplaceAll

download fail
```

**Comment by tdrozdovsky** [comment]
@t25kim @MoonkiHong I faced with this issue too. We have two options:
1. Fix the version `golang.org/x/mobile/cmd/gomobile`
2. Download the new version of Go and raise the requirements for the Go version in the documentation to 1.12. (I successfully made this option)

**Comment by MoonkiHong** [comment]
> @t25kim @MoonkiHong I faced with this issue too. We have two options:
> 
> 1. Fix the version `golang.org/x/mobile/cmd/gomobile` in `glide.yaml`
> 2. Download the new version of Go and raise the requirements for the Go version in the documentation to 1.12. (I successfully made this option)

@tdrozdovsky Please refer to the recent document update for build in terms of Go version (targeting x86_64). (`1.10 -> 1.15`)

**Comment by tdrozdovsky** [comment]
@MoonkiHong The go 1.15 version also works good. I will prepare changes to the documentation for raspberry Pi and prepare a PR
