### ISSUE TITLE
Configure secure and mnedc mode while running the image

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#168]
**Is your feature request related to a problem? Please describe.**
Currently, the edge-orchestration sets the secure and mnedc options while building the project.

**Describe the solution you'd like**
Read the environment values if the edge-orchestration runs with SECURE and MNEDC options like below.
```
docker run -it -d --privileged ... -e SECURE=true -e MNEDC=server edge-orchestration:coconut
```

**Comment by MoonkiHong** [comment]
@t25kim Thank you for the good suggestion. It seems good to me to estimate further for this proposal.
