### ISSUE TITLE
Mitigating security vulnerability analysis from LGTM

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#171]
_Originally related to PR #170 proposed by @tdrozdovsky_

**Comment by MoonkiHong** [comment]
Currently (as of Dec. 15th in KST), there are 5 issue reported from `LGTM`. So reopen this issue.

**Comment by MoonkiHong** [comment]
Currently, there is a new 1 alert generated from `LGTM`. So I would like to reopen this issue.

@tdrozdovsky Please take a look at this [issue](https://lgtm.com/projects/g/lf-edge/edge-home-orchestration-go/alerts/?mode=tree&severity=&ruleFocus=1510356156143).

**Comment by tdrozdovsky** [comment]
@MoonkiHong I have highlighted this as an issue only for solving LGTM-related issues to aggregate all fixes here
