### ISSUE TITLE
[MNEDC] Interrupt Signal Processing

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#172]
How about moving MNEDC interrupt signal processing logics( [server](https://github.com/lf-edge/edge-home-orchestration-go/blob/324b41b8759e6e50e78fa15fdf76fa4117439d48/src/controller/mnedcmgr/servercontrol.go#L172), [client](https://github.com/lf-edge/edge-home-orchestration-go/blob/324b41b8759e6e50e78fa15fdf76fa4117439d48/src/controller/mnedcmgr/clientcontrol.go#L92) ) to [sigmgr](https://github.com/lf-edge/edge-home-orchestration-go/blob/324b41b8759e6e50e78fa15fdf76fa4117439d48/src/common/sigmgr/sigmgr.go#L32)?

**Comment by MoonkiHong** [comment]
@ayush-kr @suresh-lc Please take a look at the proposal above. Seems that we have a dedicated manager `sigmgr` for taking care of all the signal processing logics.
