### ISSUE TITLE
Alternate for logmgr (GoLang logging framework)

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#182]
_Reference: https://github.com/lf-edge/edge-home-orchestration-go/issues/173#issuecomment-730330067_

The current `logmgr` imports a 3rd party library for its GoLang logging framework, but it does not have any license statement. We need to apply its alternate library which has been released under a permissive license in open source communities.

You can refer to the current `logmgr` with this topic as follows: 

https://github.com/lf-edge/edge-home-orchestration-go/blob/a18e10ea178cc4148307b521e7b6dadfd6d6984f/src/common/logmgr/logmgr.go#L25

**Comment by t25kim** [comment]
I found homeedge([config.go](https://github.com/lf-edge/edge-home-orchestration-go/blob/a18e10ea178cc4148307b521e7b6dadfd6d6984f/src/controller/servicemgr/executor/containerexecutor/config.go#L34)) uses [logrus](https://github.com/Sirupsen/logrus) as well. so I'd like to suggest to use logrus as a logging framework.

**Comment by MoonkiHong** [comment]
@t25kim Thank you for the prompt suggestion! It is under MIT License and it seems good to me.

**Comment by mgjeong** [comment]
I found the licese statement from 3rd-party logger library. It may be added a few hours ago^^.
However, I'd like to say we'd better use well-known logger  ather than somone's persnal logger. ( If I miss-understood, please let mt know. ) I don't know what loggers are mostly used for golang, so I've just searched and found some keywords such as Logrus, glog. Please consider them as alternative logger. Just my two cents.

**Comment by MoonkiHong** [comment]
@mgjeong Thank you, MJ. We will check out your proposal. As you said (and some codes in our edge-home-orchestration-go), we found `Logrus` used already in our codes.

**Comment by mgjeong** [comment]
Great. ^^

**Comment by MoonkiHong** [comment]
The current license issue is resolved since the current logger is now under Apache 2.0 license. Then the remainder is :

- Consider to go / no-go : Adopt more popular logging framework as suggested by @mgjeong.
