### ISSUE TITLE
Additional tags for project promotion

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#184]
I propose to add/remove/change tags to improve the indexing of our project and, therefore, increase the rating of the project in search engines.

**Proposed to add tags:**
orchestration
containerization
docker 
cluster-computing
container
node
data-storage
rbac
hikey960
raspberry-pi 

**Proposed to remove tags:**
edge-orchestration - name of repository

**Proposed to change name tags:**
homeiot -> iot

What do you think about it?

**Comment by MoonkiHong** [comment]
@tdrozdovsky Done. Sir!

**Comment by tdrozdovsky** [comment]
@MoonkiHong Great! Thank you! Good job!
