### ISSUE TITLE
Code Scanning with CodeQL through github Actions

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#190]
How about adding [CodeQL Analysis](https://github.com/lf-edge/edge-home-orchestration-go/security/code-scanning) to detect security issues with respect to source code?

**Comment by MoonkiHong** [comment]
This is a great suggestion! @tdrozdovsky What do you think?

**Comment by tdrozdovsky** [comment]
I think the more security checks the better.
