### ISSUE TITLE
[Build System] Applying Go Modules instead of relying on Glide

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#206]
**Is your feature request related to a problem? Please describe.**
The current edge-home-orchestration-go project is built from employing `glide`. Consequently, it is really challenging for us to employ those existing available open source projects based on the Go Modules build system. One good example is that we cannot apply the latest version of Docker Engine and the recent EdgeX features, which all are based on Go Modules. In addition to make this situation much worse, the 3rd party developers might encounter a huge difficulty in building their own applications powered by edge-home-orchestration-go, because most of them are using Go Modules instead of Glide. Especially, if there is a developer to use some subset of edge-home-orchestration-go, he/she should fully describe the regarding GitHub url about those subset packages into their `import` like `github.com/lf-edge/edge-home-orchestration-go/src/common/logmgr` instead of `common/logmgr`.

**Describe the solution you'd like**
Applying the new build system based on Go Modules and deprecating the Glide based build system.

- https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md
- https://github.com/golang/go/wiki/Modules

**Suggestion: LET US discuss this issue in the upcoming TSC online meeting in January 2021!!!**

**Comment by t25kim** [comment]
I deeply agree that this issue should be resolved.
I will open a PR regarding this as soon as possible for ease of discussion.

**Comment by suresh-lc** [comment]
Good point brought out. We can discuss on this regard on Glide and Go Module on Jan month TSC call as mentioned.

**Comment by suresh-lc** [comment]
Came across a blog and seems good one : https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md

**Comment by MoonkiHong** [comment]
> Came across a blog and seems good one : https://blog.golang.org/migrating-to-go-modules

@suresh-lc PTAL specifically about #210!
