### ISSUE TITLE
[Upgrade policy for attributes packages] Version upgrade policy & Docker Engine upgrade

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#207]
**Is your feature request related to a problem? Please describe.**
In order to apply the Go Modules based build system, our current Docker Engine (v17.xx.xx) is too old to be compatible with other packages. In addition to that, this version (v17.xx.xx) has some issue from its dedicate community to **Archive** since it is too old (https://github.com/docker/go-docker/issues/21). Meanwhile, it is a bit troublesome to adopt the latest version of Docker Engine, because it is not yet touching the maturity level.

- This issue is also linked to #206 

**Describe the solution you'd like**
Update the current Docker Engine to at least v19.xx.xx and establish the official upgrade policy (annual basis in the regular release) about Docker Engine and other relying attributes packages from other open source projects.

**Suggestion: LET US discuss this issue in the upcoming TSC online meeting in January 2021!!!**

**Comment by t25kim** [comment]
This project is related to other open source projects such as docker, edgexfoundry at the moment.
It would be nice if we have an annual version update period for the upstream projects.

**Comment by MoonkiHong** [comment]
> This project is related to other open source projects such as docker, edgexfoundry at the moment.
> It would be nice if we have an annual version update period for the upstream projects.

@t25kim Thank you for supporting this idea! Plus, we should publish a document from GitHub and/or the dedicated Wiki aout that dependency metrics in terms of correlated open source projects (libraries) and their referencing version as well. If we get enough consent, I will draft that as well.

**Comment by tdrozdovsky** [comment]
I completely agree! Thank you @t25kim! The only thing I would like is that we first fix bugs in testing packages within the project and add automated testing.

**Comment by MoonkiHong** [comment]
It is resolved after the PR merger of #210, so closed. Thank you all.
