### ISSUE TITLE
[Secure] Local Image Execution

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#215]
Is there any way to run local container images in `secure` mode if `DIGEST` of the image is `<none>`?

**Comment by tdrozdovsky** [comment]
@t25kim In `secure` mode, we cannot run unknown containers (without a `DIGEST`)

**Comment by t25kim** [comment]
@tdrozdovsky Thank you for the prompt answer!
Do you think HomeEdge doesn't need to run local images for the developers?
I think it might be good for developers to have the method to enable or disable the `verifier` in secure mode.

**Comment by tdrozdovsky** [comment]
There is a `normal` mode (without security) for developers. We cannot allow containers to run without a `DIGEST`. But in the future, when we add a digital signature of `containerWhiteList`, we can consider this option.

**Comment by t25kim** [comment]
@tdrozdovsky I thought there might be a developer wants to test his dev container in local PC with HTTPS and RBAC. Just my 2 cents. 😁
