### ISSUE TITLE
More details of how does the system run on a android device

### ISSUE THREAD

**Issue by DoomsdayT** [lf-edge/edge-home-orchestration-go#241]
I am wondering how do you let the android phone run as a computing device.

**Comment by MoonkiHong** [comment]
@DoomsdayT Thank you for your interests. I believe that the details could be explained by one of our colleagues @suresh-lc.

**Comment by suresh-lc** [comment]
@DoomsdayT : Nice to hear from you of your interest in using Home Edge in Android. As such the Open Source release supports Linux. We do have tried building the Home Edge as .aar and using with android application. https://github.com/lf-edge/edge-home-orchestration-go/blob/master/src/interfaces/javaapi/javaapi.go, could be of some interest to you.
For more details on steps for Android might be, can share via email the details.

**Comment by suresh-lc** [comment]
@DoomsdayT : Wanted to check if you tried Home Edge & Android.

**Comment by suresh-lc** [comment]
@DoomsdayT : Basic version of Home Edge for Android is now officially available at [Home Edge Android](https://github.com/lf-edge/edge-home-orchestration-android/releases/tag/0.1.0)
