### ISSUE TITLE
[Static Analysis] Integration of SonarCloud for CII BP Badge process

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#254]
- Cross reference from @tdrozdovsky: https://github.com/lf-edge/edge-home-orchestration-go/pull/251#discussion_r567477862

**Comment by t25kim** [comment]
@tdrozdovsky @MoonkiHong How about adding a `.sonarcloud.properties` file for [configuration](https://sonarcloud.io/documentation/analysis/automatic-analysis/#additional-analysis-configuration)?
It would be great if we exclude unnecessary files related test, vendor, and so on. 
Please refer the edgex-go case below. 
 - [edgex-go properties file](https://github.com/edgexfoundry/edgex-go/blob/master/.sonarcloud.properties)
 - [edgex-go sonarcloud](https://sonarcloud.io/dashboard?id=edgexfoundry_edgex-go)

**Comment by tdrozdovsky** [comment]
@t25kim This is a great idea!
