### ISSUE TITLE
Using Internal wiki of edge-home-orchestration-go

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#261]
Let's consider the use of a wiki in our repository, not for duplicating information from https://wiki.lfedge.org/display/HOME/Roadmap+and+Release+Notes, but for FAQ, useful links and additional instructions for our repository? 

Good example: https://github.com/beefproject/beef/wiki

**Comment by t25kim** [comment]
There is no reason not to use it.
I have no content at the moment, however I will use the wiki if I have useful information for users.
If you have something useful, please write it on the wiki.
