### ISSUE TITLE
[MNEDC] Security Hotspots detected by SonarCloud

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#273]
[SonarCloud detects hardcoded IP address.](https://sonarcloud.io/component_measures?id=lf-edge_edge-home-orchestration-go&metric=new_security_review_rating&pullRequest=272&view=list)

![image](https://user-images.githubusercontent.com/5847128/108348063-a9515180-7224-11eb-8464-12930346203e.png)

**Comment by MoonkiHong** [comment]
@t25kim This is a great catch! Thank you for your analysis!

**Comment by MoonkiHong** [comment]
@suresh-lc @sun-sharma Think that this should be resolved immediately. Would like to get your thoughts! Thank you in advance.

**Comment by suresh-lc** [comment]
@MoonkiHong : Thanks for notifying on the issue. Have checked on the cause of the issue.  Will start working on this soon.
