### ISSUE TITLE
[Refactoring] Build script

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#278]
How about refactoring `build.sh` file a little bit shorter?
- [x] Remove [`PKG_LIST`](https://github.com/lf-edge/edge-home-orchestration-go/blob/ae413fe2ecb3eb9176d862117b476c7f26431f99/build.sh#L9) and use a relative path to run test scenarios.
- [ ] Streamline code in terms of `BUILD_TAGS` such as `secure`, `mnedc`.
- [ ] Delete duplicated code that can be eliminated

**Comment by suresh-lc** [comment]
Good idea, we can remove duplicated code and check on refactoring the file. Check for all the functions and might be make separate .sh for functions. Just my thought, need to investigate how much it would add value. Lets check on refactoring to make build script simple and understandable.

**Comment by tdrozdovsky** [comment]
I think that BUILD_TAGS: secure should be enabled by default (and I will try to do it soon). But for ease of development, I plan to add a BUILD_TAGS:unsecure, but only as a tag for the build!

**Comment by t25kim** [comment]
> I think that BUILD_TAGS: secure should be enabled by default (and I will try to do it soon). But for ease of development, I plan to add a BUILD_TAGS:unsecure, but only as a tag for the build!

@tdrozdovsky Thank you for sharing your idea. I hope to set `secure` as a default. 
In order to do so, it seems that the usability of Security Manager should be improved.
Let's talk about security components like [Verifier](https://github.com/lf-edge/edge-home-orchestration-go/blob/bb49416e134e68696a9c8d27e58c69620b330de6/docs/secure_manager.md#2-verifier) and [Authenticator](https://github.com/lf-edge/edge-home-orchestration-go/blob/bb49416e134e68696a9c8d27e58c69620b330de6/docs/secure_manager.md#3-authenticator) by opening a new issue.
