### ISSUE TITLE
[SUSPENDED] Ubuntu Version

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#289]
[Standard support for Ubuntu 16.04 LTS](https://wiki.ubuntu.com/Releases) ends in April 2021.
I'd like to
 1. exclude Ubuntu 16.04 from the [Build](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/.github/workflows/build.yml) and [Test Suite](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/.github/workflows/test-suite.yml) workflows.
 2. change the Ubuntu version of the [Dockerfile](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/Dockerfile) from 16.04 to 20.04.

**Comment by tdrozdovsky** [comment]
I see that there are already some problems with ubuntu 16.04

**Comment by t25kim** [comment]
> I see that there are already some problems with ubuntu 16.04

@tdrozdovsky You're right. I noticed problems due to your PR #287 , #288. 
Could you revise code in terms of workflows?

Regarding Dockerfile change, I'd like to give a chance for a new contributor.

**Comment by tdrozdovsky** [comment]
> @tdrozdovsky You're right. I noticed problems due to your PR #287 , #288.
> Could you revise code in terms of workflows?

Yes of course I will do it

**Comment by tdrozdovsky** [comment]
> Regarding Dockerfile change, I'd like to give a chance for a new contributor.

@t25kim  What do you have in mind?

**Comment by t25kim** [comment]
> > Regarding Dockerfile change, I'd like to give a chance for a new contributor.
> 
> @t25kim What do you have in mind?

I'm going to have a toy project with some university students and would like to guide them how to contribute to open source through HomeEdge. I think changing the ubuntu version in Dockerfile is one of good contributing points.

**Comment by tdrozdovsky** [comment]
While the github->Actions under Ubuntu-16.04 are working. Therefore, this issue is suspended.
In case of problems with the github->Actions under Ubuntu-16.04, the PR #290 is ready and can be applied as soon as possible

**Comment by t25kim** [comment]
> While the github->Actions under Ubuntu-16.04 are working. Therefore, this issue is suspended.
> In case of problems with the github->Actions under Ubuntu-16.04, the PR #290 is ready and can be applied as soon as possible

In my opinion, no matter if workflows run or not, it would be nice to exclude the os if it ends standard support period.
