### ISSUE TITLE
Use Staticcheck instead of golint

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#323]
_NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as [Staticcheck](https://staticcheck.io/) and go vet should be used instead._ from https://github.com/golang/lint/blob/master/README.md

**Comment by tdrozdovsky** [comment]
@t25kim This is a very good idea. I have already started using _Staticcheck_ for analysis. There are many comments from the _Staticcheck_ and I will try to fix the part in the near future and turn on the _Staticcheck_ for automatic analysis.

**Thank you for advised it!**

On the other hand, I propose a lint to not be excluded as it is also useful and used in the Go report system and we have the lowest indicators on it. **golint->76%** (https://goreportcard.com/report/github.com/lf-edge/edge-home-orchestration-go).
