### ISSUE TITLE
[DataStorage] Upgrade to EdgeX v2.0 (Ireland)

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#324]
We should get out of [temporary use](https://github.com/lf-edge/edge-home-orchestration-go/blob/34ad844318457cb2cbae5d359cfa1d6ec0998411/go.mod#L5) and need to check the possibility of official EdgeX v2.0 for Home Edge.

**Comment by t25kim** [comment]
I made the `ds_ireland` branch to test DataStorage with edgex v2.0. 

1. Run EdgeX containers without security 
```
$ cd deployments/datastorage
$ docker-compose up -d
```
2. Save configuration files to `/var/edge-orchestration/datastorage/`
3. Create the container image
```
./build.sh container x86_64
```
4. Run edge-orchestration 
```
docker run -it -d --privileged --network="host" --name edge-orchestration -e EDGEX_SECURITY_SECRET_STORE=false -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro edge-orchestration:coconut
```

**Comment by MoonkiHong** [comment]
> I made the `ds_ireland` branch to test DataStorage with edgex v2.0.
> 
> 1. Run EdgeX containers without security
> 
> ```
> $ cd deployments/datastorage
> $ docker-compose up -d
> ```
> 
> 1. Save configuration folders and files in [configs/datastorage folder](https://github.com/lf-edge/edge-home-orchestration-go/tree/ds_ireland/configs/datastorage) to `/var/edge-orchestration/datastorage/`
> 2. Create the container image
> 
> ```
> $ ./build.sh container x86_64
> ```
> 
> 1. Run edge-orchestration
> 
> ```
> $ docker run -it -d --privileged --network="host" --name edge-orchestration -e EDGEX_SECURITY_SECRET_STORE=false -v /var/edge-orchestration/:/var/edge-orchestration/:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /proc/:/process/:ro edge-orchestration:coconut
> ```

@t25kim This is really a nice approach.

**Comment by MoonkiHong** [comment]
@sun-sharma PTAL. (including #326) in terms of the test w.r.t. the PR.

**Comment by MoonkiHong** [comment]
@tdrozdovsky PTAL in terms of build methodology from the impact of EdgeX v2.0 upgrade.

**Comment by tdrozdovsky** [comment]
> 
> 
> @tdrozdovsky PTAL in terms of build methodology from the impact of EdgeX v2.0 upgrade.

When a new build system is accepted, we can easily add any options

**Comment by sun-sharma** [comment]
Hi @t25kim , 

I have been facing errors while trying to build using 
`$ ./build.sh container x86_64`

Earlier I was getting errors related to ZMQ
```

# pkg-config --cflags  -- libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
make: *** [Makefile:67: build-binary] Error 1
```

I tried doing the necessary installs

```
wget https://github.com/zeromq/libzmq/releases/download/v4.2.1/zeromq-4.2.1.tar.gz
tar -xvzf zeromq-4.2.1.tar.gz
cd zeromq-4.2.1/

sudo apt-get install libtool pkg-config build-essential autoconf automake uuid-dev
sudo apt-get install checkinstall

./configure
make
sudo checkinstall
sudo ldconfig
```

Now, while building I am getting runtime errors
```

runtime: unexpected return pc for cmd/compile/internal/ssa.rewriteValuegeneric_OpLess32 called from 0x0
stack: frame={sp:0xc000161658, fp:0xc000161688} stack=[0xc00015e000,0xc000166000)
```

Did you encounter such issues ?

**Comment by t25kim** [comment]
> Hi @t25kim ,
> 
> I have been facing errors while trying to build using
> `$ ./build.sh container x86_64`
> 
> Earlier I was getting errors related to ZMQ
> 
> ```
> 
> # pkg-config --cflags  -- libzmq
> Package libzmq was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libzmq.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libzmq' found
> pkg-config: exit status 1
> make: *** [Makefile:67: build-binary] Error 1
> ```
> 
> I tried doing the necessary installs
> 
> ```
> wget https://github.com/zeromq/libzmq/releases/download/v4.2.1/zeromq-4.2.1.tar.gz
> tar -xvzf zeromq-4.2.1.tar.gz
> cd zeromq-4.2.1/
> 
> sudo apt-get install libtool pkg-config build-essential autoconf automake uuid-dev
> sudo apt-get install checkinstall
> 
> ./configure
> make
> sudo checkinstall
> sudo ldconfig
> ```
> 
> Now, while building I am getting runtime errors
> 
> ```
> 
> runtime: unexpected return pc for cmd/compile/internal/ssa.rewriteValuegeneric_OpLess32 called from 0x0
> stack: frame={sp:0xc000161658, fp:0xc000161688} stack=[0xc00015e000,0xc000166000)
> ```
> 
> Did you encounter such issues ?

Please install 0mq with apt-get like below.
```
$ sudo apt-get install -y libzmq3-dev
```

**Comment by MoonkiHong** [comment]
@suresh-lc @nitu-s-gupta @tdrozdovsky @t25kim Since EdgeX `Ireland` release seems to change a lot of APIs, it might be numerous items for us to update from our side if we refer to the `Ireland` for the upcoming release. I would like to make a decision how we select the target version of downstream projects like EdgeX Foundry for our Dewberries release. Happy to get your opinion shortly. 🙏

**Comment by t25kim** [comment]
EdgeX v2.1(Jakarta) has been released. We will think of what version of edgex should be taken.
