### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by nandeesh54** [lf-edge/edge-home-orchestration-go#34]
orchestration link is not responding. Is there any possibility to get access to that link or any other solution.

**Comment by wansuyoo** [comment]
Hi. fixed the link for image of tar archive to current github release.

**Comment by MoonkiHong** [comment]
Seems that this is resolved by fixing the given image link from the "Release" tap (https://github.com/lf-edge/edge-home-orchestration-go/issues/34#issuecomment-528119170), so we would like to close this issue. Please let us know if there is any regarding issue for this.
