### ISSUE TITLE
jwt Package Version Upgrade

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#344]
We need to change the jwt pakcage path and version becuase of maintenance and security issues. 
Please see the jwt's [README.md](https://github.com/golang-jwt/jwt#jwt-go).

**Comment by tdrozdovsky** [comment]
@t25kim Thank you very much, I knew about these problems before. We do not use this package in problem modes. But I planned to update them as soon as corrections appear. I will study may have time to do it.

Thanks for all your efforts and for supporting me in security area!
