### ISSUE TITLE
Testing Guide Update 

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#350]
[Testing Policy](https://github.com/lf-edge/edge-home-orchestration-go/blob/6bc65c06d21b1c46f64818521f5ab3a22adab9a2/docs/testing_policy.md) should have how to install coverage tool (gocov and gocov-html).

**Error Log when coverage tools are not installed.**
```
t25kim@t25kim:~/work/edge-home-orchestration-go$ make test
.
.
--------------------------------------
  build test for internal/...
--------------------------------------
make test-go TEST_PKG_DIRS="internal/..."
make[1]: Entering directory '/home/t25kim/work/edge-home-orchestration-go'
gocov test -v ./internal/... > coverage.out
/bin/sh: 1: gocov: not found
```
```
t25kim@t25kim:~/work/edge-home-orchestration-go$ go get github.com/axw/gocov/gocov
go get: added github.com/axw/gocov v1.0.0
t25kim@t25kim:~/work/edge-home-orchestration-go$ make test
.
.
github.com/lf-edge/edge-home-orchestration-go/internal/restinterface/tls/tls.go  SetHandler                              0.00% (0/1)
github.com/lf-edge/edge-home-orchestration-go/internal/restinterface/tls         -------------------------------------   94.44% (17/18)

Total Coverage: 73.75% (3071/4164)
gocov-html coverage.out > coverage.html
/bin/sh: 1: gocov-html: not found
```

**Comment by tdrozdovsky** [comment]
@t25kim [Testing policy](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/testing_policy.md) has been updated in #345

**Comment by t25kim** [comment]
> 
> 
> @t25kim [Testing policy](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/testing_policy.md) has been updated in #345

Sorry. I missed that PR. 
I've updated the issue in terms of installation of coverage tools.

**Comment by tdrozdovsky** [comment]
I fix it as soon as possible
