### ISSUE TITLE
create Docker container fail

### ISSUE THREAD

**Issue by nandeesh54** [lf-edge/edge-home-orchestration-go#36]
while executing the ./build.sh file in Ubuntu 16.04(x86_64). I got the following error
**********************************
 Create Docker container 
**********************************
edge-orchestration
Untagged: edge-orchestration:alpha
Deleted: sha256:c533b88f3523957580cf73b76219b17ba7db52ccaebd84f19da596fab3e063ec
Deleted: sha256:1f2237144efc2ffef4098f24147c617655c87f1db8d647421e482120e4ce285d
Deleted: sha256:27e58b236a7c06911b99229175562fc59df2e8512dfdea8b22468df74af91fa0
Deleted: sha256:ba7320ba8a6fe7a0763dd7bb6fd491af5f471c77e697be4a0eafd0e26086dead
docker build --tag edge-orchestration:alpha --file /home/Documents/mec/edge-home-orchestration-go/GoMain/Dockerfile .
Sending build context to Docker daemon  260.8MB
Step 1/16 : FROM ubuntu:16.04
 ---> 5e13f8dd4c1a
Step 2/16 : ENV TARGET_DIR=/edge-orchestration
 ---> Using cache
 ---> ac9bd4191d91
Step 3/16 : ENV HTTP_PORT=56001
 ---> Using cache
 ---> eaed1ac412ca
Step 4/16 : ENV MDNS_PORT=5353
 ---> Using cache
 ---> a7721d9a78e7
Step 5/16 : ENV ZEROCONF_PORT=42425
 ---> Using cache
 ---> bc930482e7d5
Step 6/16 : ENV APP_MAIN_DIR=GoMain
 ---> Using cache
 ---> a3ae31bec427
Step 7/16 : ENV APP_BIN_DIR=$APP_MAIN_DIR/bin
 ---> Using cache
 ---> c38738405bbb
Step 8/16 : ENV APP_NAME=edge-orchestration
 ---> Using cache
 ---> 6a80fbb4f830
Step 9/16 : COPY $APP_BIN_DIR/$APP_NAME $APP_MAIN_DIR/run.sh $TARGET_DIR/
 ---> d9d3c9b20f41
Step 10/16 : EXPOSE $HTTP_PORT $MDNS_PORT $ZEROCONF_PORT
 ---> Running in c3b48ac48abb
Removing intermediate container c3b48ac48abb
 ---> ac5ee5bac7b5
Step 11/16 : RUN mkdir -p /var
 ---> Running in 9aad0c66fd6c
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: invalid argument\"": unknown
Makefile:93: recipe for target 'build-container' failed
make: *** [build-container] Error 1

**Comment by wansuyoo** [comment]
@nandeesh54 
Hi. how about your runc version on host pc for building?
Please check it like as below.
$ runc --version

**Comment by nandeesh54** [comment]
after running above command. I got version as below
runc version 1.0.0-rc8
commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
spec: 1.0.1-dev

**Comment by MoonkiHong** [comment]
@nandeesh54 Did you solve your issue reported here. If not, please let us know about your problem currently.

**Comment by MoonkiHong** [comment]
Since it seems to be dormant, I close this issue at this moment. (Will be initiated by anyone who want to clarify this issue again)
