### ISSUE TITLE
Demo Video

### ISSUE THREAD

**Issue by mchittineni** [lf-edge/edge-home-orchestration-go#361]
Hi, I'm looking for a demo video to through the project in a sequential manner.

Can anybody help me please

Thank You!!

**Comment by MoonkiHong** [comment]
@nitu-s-gupta PTAL. 😄

**Comment by MoonkiHong** [comment]
We have an official webinar from YouTube, so at this moment, I close this issue and will follow up the similar request next time once we have again.
