### ISSUE TITLE
Not Able to load the tar file onto docker repository

### ISSUE THREAD

**Issue by mchittineni** [lf-edge/edge-home-orchestration-go#362]
Test environment configuration (please complete the following information):
Firmware version: Ubuntu 18.04 Bionic on VM Station Pro
Hardware: x86-64, ARM, Intel i7 - 8th Gen, RAM size - 2 GB
Toolchain: Docker
Edge Orchestration Release: GO

Hi, I'm not able to load the edge-orchestration.tar file onto the Docker Repository.
System is showing me the error: No such file or Directory.

Can anyone please help me with this issue please.

**Comment by MoonkiHong** [comment]
@mchittineni Thank you for your interest. 

@nitu-s-gupta This issue is related to #361. PTAL. 😄
