### ISSUE TITLE
[Release Code Name] vD

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#372]
We are about to release the next regular release which will have its code name starting from D. As we have released our regular releases with a concept of the fruit name, I would like to suggest several candidates as follows:

- Dates
- Dragonfruit
- Durian
- Dewberries

@t25kim @tdrozdovsky @suresh-lc @suresh-lc Let me know your preference.

**Comment by tdrozdovsky** [comment]
+ Dewberries

**Comment by t25kim** [comment]
- Durian +1
- Dewberries +1

**Comment by MoonkiHong** [comment]
Currently leaderboard:
- Dewberries: 2
- Durian: 1

@suresh-lc @nitu-s-gupta Any preference from you? 🙏

**Comment by nitu-s-gupta** [comment]
Dewberries

**Comment by MoonkiHong** [comment]
Currently leaderboard:

- Dewberries: 3
- Durian: 1

@suresh-lc We are waiting for your vote! 😁

**Comment by MoonkiHong** [comment]
@t25kim @tdrozdovsky @nitu-s-gupta @suresh-lc Let us pick `Dewberries` as a codename of our upcoming D release! Its semantic version will be `2.0.0`. Please let me know if you approve this. 🙏

**Comment by tdrozdovsky** [comment]
Based on the [principles of semantic versioning](https://semver.org/), I think that the next version should be v1.1.0.

**Comment by MoonkiHong** [comment]
@tdrozdovsky Makes sense. Let us fix the upcoming semantic release as v1.1.0. Sorry for a confusion. Congrats for our new release code name "Dewberries". 😁
