### ISSUE TITLE
Import edgexfoundry/device-sdk-go to the third_party folder

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#386]
Edge Orchestration uses edgexfoundry/device-sdk-go from github.com/hahattan/device-sdk-go v1.4.1, not the official repository. 
I would like to discuss copying the source code to the third_party folder since upgrading Ireland release is difficult and there might be several issues at the moment.

**Comment by MoonkiHong** [comment]
There is a suggestion from TAC Chair (Jim St. Ledger) that EdgeX is operating a long-term-service (LTS) of the certain release and we are not sure that the v1.4.1 of `device-sdk-go` from EdgeX is included in their LTS. 

@suresh-lc What do you think of this idea? Anyway we must something to EdgeX as our requirement to their milestone.

**Comment by MoonkiHong** [comment]
@NiranjanPatil25 Please feel free to let us know your opinion. 🙏

**Comment by suresh-lc** [comment]
> There is a suggestion from TAC Chair (Jim St. Leger) that EdgeX is operating a long-term-service (LTS) of the certain release and we are not sure that the v1.4.1 of `device-sdk-go` from EdgeX is included in their LTS.
> 
> @suresh-lc What do you think of this idea? Anyway we must do something to EdgeX as our requirement to their milestone.

@MoonkiHong : Thanks for the inputs from Jim. Understand the motivation behind moving to third_party folder. Regarding our requirements and dependency to EdgeX, guess we can have discussion on the same post the vD release.

**Comment by MoonkiHong** [comment]
> There is a suggestion from TAC Chair (Jim St. Leger) that EdgeX is operating a long-term-service (LTS) of the certain release and we are not sure that the v1.4.1 of `device-sdk-go` from EdgeX is included in their LTS.
> 
> @suresh-lc What do you think of this idea? Anyway we must do something to EdgeX as our requirement to their milestone.

We **MUST** make a decision on this before our Dewberries release, since `device-sdk-go` is not official, so if an owner of this repo deletes it, we cannot build our package.

**Comment by tdrozdovsky** [comment]
My opinion is as follows: we work closely with the EdgeX, therefore, if possible, we must adapt the code under the `Ireland` long-term-service (LTS). Otherwise, we will have to constantly include the code into our repository and support it.

**Comment by t25kim** [comment]
> 
> 
> My opinion is as follows: we work closely with the EdgeX, therefore, if possible, we must adapt the code under the `Ireland` long-term-service (LTS). Otherwise, we will have to constantly include the code into our repository and support it.

My intention in this issue is only for the Dewberries release. 
Releasing vD with [temporary use the hahattan repo](https://github.com/lf-edge/edge-home-orchestration-go/blob/bd4e0ddba4d85919ae0979998a57fe2380720e3c/go.mod#L5) may cause `build break` when the hahattan deletes the personal repository. To avoid the problem, I'd like to copy `device-sdk-go` under third_party folder for temporary use. 
For reference, the source code under the third_party folder mean temporary.
**I hope all the code under third_party folder should be deleted from vE release.**

**Comment by MoonkiHong** [comment]
> > My opinion is as follows: we work closely with the EdgeX, therefore, if possible, we must adapt the code under the `Ireland` long-term-service (LTS). Otherwise, we will have to constantly include the code into our repository and support it.
> 
> My intention in this issue is only for the Dewberries release.
> Releasing vD with [temporary use the hahattan repo](https://github.com/lf-edge/edge-home-orchestration-go/blob/bd4e0ddba4d85919ae0979998a57fe2380720e3c/go.mod#L5) may cause `build break` when the hahattan deletes the personal repository. To avoid the problem, I'd like to copy `device-sdk-go` under third_party folder for temporary use.
> For reference, the source code under the third_party folder mean temporary.
> **I hope all the code under third_party folder should be deleted from vE release.**

I love this idea, but hope to get consensus with all of you. 🙏

**Comment by t25kim** [comment]
Instead of copying the code, we use official edgexfoundry/device-sdk-go v1.4.0 and fix the [bug](https://github.com/lf-edge/edge-home-orchestration-go/issues/231).
