### ISSUE TITLE
Remove Heterogeneous Container Image Build Instructions

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#412]
How about removing the heterogeneous image build instructions from documentations for ease of use and maintainability? 
 - [RPi3 example](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#1-using-your-pc)

**Pros**
The process of configuration file creation could be removed and it is very efficient to beginners.
Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.

**Comment by tdrozdovsky** [comment]
I **strongly recommend not to remove 1 approach** from documentation.

1) The documentation clearly describes [two options for build of edge-orchestration project](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#how-to-build)

2) Most developers use exceptionally the first option (сonveniently developing on PC: any IDE and fast compilation are available).

3) All platforms support the build using the 1 approach. The 2 is optional. (Frankly I added an second approach to build only for product promotion and better indexing in search engines)  

4) At the first approach there are cross-references from the RaspberryPi cluster. 

5) Often there are delays with updating packages for arm32v7 arch. (we had an example with golang)

P.S.  If there is a thought: Why do we support other architectures? I want to note that most home devices except the PC are based on the **arm**. Therefore, this **is a target platform for us**.

**Comment by smarthome-hanium** [comment]
@tdrozdovsky Thanks for sharing your thought. Your opinion will be very helpful in determining the direction.

> 1. The documentation clearly describes [two options for build of edge-orchestration project](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#how-to-build)

The document is not immutable, and we can change it according to the agreement. Because of the reason, I've opened this issue up.

> 2. Most developers use exceptionally the 1 approach (сonveniently developing on PC: any IDE and fast compilation are available).

If the compilation time is too long, you must be right. I took the same approach. However this project's compilation time is not long. 
Please do not generalize too much. There are also many people who want it to be built automatically according to os architecture with a simple command of "make" without manual configuration. 

> 3. All platforms support the build using the 1 approach. The 2 is optional. (Frankly I added an second approach to build only for product promotion and better indexing in search engines)

Not all projects support 1 approach. 
The [build guide](https://docs.edgexfoundry.org/1.3/getting-started/Ch-GettingStartedGoDevelopers/#build-edgex-foundry) from EdgeX Foundry which support arm architecture describe approach 2 only. 
The connectedhomeip doesn't have the heterogenous build instruction and guide to [build on RPi](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#installing-prerequisites-on-raspberry-pi-4).
The k3s also supports [various architectures](https://github.com/k3s-io/k3s#manual-download) but it has only [simple build instruction](https://github.com/k3s-io/k3s/blob/master/BUILDING.md).

> 4. At the first approach there are cross-references from the RaspberryPi cluster.

In this case, I agree. Approach 1 is more useful. If possible, we can guide the alternative of uploading the container image to docker hub for private use. 

> 5. Often there are delays with updating packages for arm32v7 arch. (we had an example with golang)
> 

I don't understand why this is a problem. This issue is not intended to abandon arm architectures. 

> P.S. If there is a thought: Why do we support other architectures? I want to note that most home devices except the PC are based on the **arm**. Therefore, this **is a target platform for us**.

This issue is not intended to abandon arm architectures. We are going to distribute various os architecture container images and developers can download arm architecture images from docker hub.

@NiranjanPatil25 @suresh-lc Please share your thoughts on this issue.

**Comment by t25kim** [comment]
@tdrozdovsky Thanks for sharing your thought. Your opinion will be very helpful in determining the direction.

> 1. The documentation clearly describes [two options for build of edge-orchestration project](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#how-to-build)

The document is not immutable, and we can change it according to the agreement. Because of the reason, I've opened this issue up.

> 2. Most developers use exceptionally the 1 approach (сonveniently developing on PC: any IDE and fast compilation are available).

If the compilation time is too long, you must be right. I took the same approach. However this project's compilation time is not long. 
Please do not generalize too much. There are also many people who want it to be built automatically according to os architecture with a simple command of "make" without manual configuration. 

> 3. All platforms support the build using the 1 approach. The 2 is optional. (Frankly I added an second approach to build only for product promotion and better indexing in search engines)

Not all projects support 1 approach. 
The [build guide](https://docs.edgexfoundry.org/1.3/getting-started/Ch-GettingStartedGoDevelopers/#build-edgex-foundry) from EdgeX Foundry which support arm architecture describe approach 2 only. 
The connectedhomeip doesn't have the heterogenous build instruction and guide to [build on RPi](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#installing-prerequisites-on-raspberry-pi-4).
The k3s also supports [various architectures](https://github.com/k3s-io/k3s#manual-download) but it has only [simple build instruction](https://github.com/k3s-io/k3s/blob/master/BUILDING.md).

> 4. At the first approach there are cross-references from the RaspberryPi cluster.

In this case, I agree. Approach 1 is more useful. If possible, we can guide the alternative of uploading the container image to docker hub for private use. 

> 5. Often there are delays with updating packages for arm32v7 arch. (we had an example with golang)
> 

I don't understand why this is a problem. This issue is not intended to abandon arm architectures. 

> P.S. If there is a thought: Why do we support other architectures? I want to note that most home devices except the PC are based on the **arm**. Therefore, this **is a target platform for us**.

This issue is not intended to abandon arm architectures. We are going to distribute various os architecture container images and developers can download arm architecture images from docker hub.

@NiranjanPatil25 @suresh-lc Please share your thoughts on this issue.

**Comment by MoonkiHong** [comment]
+ @nitu-s-gupta

**Comment by tdrozdovsky** [comment]
> 
> 
> How about removing the heterogeneous image build instructions from documentations for ease of use and maintainability?
> 
>     * [RPi3 example](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#1-using-your-pc)
> 
> 
> **Pros** The process of configuration file creation could be removed and it is very efficient to beginners. Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.



> The process of configuration file creation could be removed and it is very efficient to beginners.

The process of configuration file creation is present in both options.

**Comment by tdrozdovsky** [comment]
> Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.

Using this mode we test the build during each PR for all architectures.

**Comment by t25kim** [comment]
> 
> 
> > How about removing the heterogeneous image build instructions from documentations for ease of use and maintainability?
> > ```
> > * [RPi3 example](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/raspberry_pi3/raspberry_pi3.md#1-using-your-pc)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Pros** The process of configuration file creation could be removed and it is very efficient to beginners. Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.
> 
> > The process of configuration file creation could be removed and it is very efficient to beginners.
> 
> The process of configuration file creation is present in both options.

Yes, that's right. I'd like to remove the process of configuration file creation if heterogeneous build is not maintained officially.

**Comment by tdrozdovsky** [comment]
In this case, how to collect under other architecture?

**Comment by tdrozdovsky** [comment]
What do you mean under "heterogeneous build"?

**Comment by tdrozdovsky** [comment]
I sincerely want to understand your motivation!

**Comment by t25kim** [comment]
> 
> 
> > Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.
> 
> Using this mode we test the build during each PR for all architectures.

@tdrozdovsky You're right. For this reason, we should support the heterogeneous build. 

How about removing .config instead? I think we can use [buildx](https://github.com/docker/buildx) for multi-platform image.
Also we can push images to docker hub automatically with [docker/build-push-action](https://github.com/docker/build-push-action).

**Comment by t25kim** [comment]
> 
> 
> I sincerely want to understand your motivation!

I want everything to run automatically with a little effort. 😁

**Comment by tdrozdovsky** [comment]
> 
> 
> > > Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.
> > 
> > 
> > Using this mode we test the build during each PR for all architectures.
> 
> @tdrozdovsky You're right. For this reason, we should support the heterogeneous build.
> 
> How about removing .config instead? I think we can use [buildx](https://github.com/docker/buildx) for multi-platform image. Also we can push images to docker hub automatically with [docker/build-push-action](https://github.com/docker/build-push-action).

I thought about using the buildx earlier, in this case I do not understand how we will build a native and android part

**Comment by t25kim** [comment]
> > > > Maintainers don't have to consider heterogeneous build, so they can focus on other tasks.
> > > 
> > > 
> > > Using this mode we test the build during each PR for all architectures.
> > 
> > 
> > @tdrozdovsky You're right. For this reason, we should support the heterogeneous build.
> > How about removing .config instead? I think we can use [buildx](https://github.com/docker/buildx) for multi-platform image. Also we can push images to docker hub automatically with [docker/build-push-action](https://github.com/docker/build-push-action).
> 
> I thought about using the buildx earlier, in this case I do not understand how we will build a native and android part

We can use the buildx only for building container images, not native and not android.
How about building the native library with the "make native"? For android, "make android"?
Of course, "make" builds the container image according to the os architecture.

**Comment by tdrozdovsky** [comment]
I think that if change something, then on the use of docker multi-stage build (harder to maintenance, but easier when used).

**Comment by t25kim** [comment]
> 
> 
> I think that if change something, then on the use of docker multi-stage build (harder to maintenance, but easier when used).

@tdrozdovsky I thought we should use the docker multi-stage build. 

Can we summarize it as follows?
1. Keep both build approaches in the documentation.
2. The configuration process could be removed.
  - "make" : build the container image according to the os architecture
  - "make native" : build the native library
  - "make android" : build the android library
  - "make container --platform=<os architecture>" : build the container image in terms of os architecture

**Comment by tdrozdovsky** [comment]
How to specify the basic image for container?

**Comment by t25kim** [comment]
> How to specify the basic image for container?

@tdrozdovsky What does `basic` mean? Are you asking if it's Ubuntu or Alpine?

**Comment by tdrozdovsky** [comment]
yes

**Comment by t25kim** [comment]
> yes

Of course, the basic image is ubuntu at the moment.

**Comment by tdrozdovsky** [comment]
We do delete the opportunity to use other images?

**Comment by t25kim** [comment]
> We do delete the opportunity to use other images?

No. The alpine docker file will not be deleted. 
We distribute ubuntu image from docker hub, so ubuntu is the official container image at the moment.
If any developer who want to use alpine image, he/she can use alpine Dockerfile.

**Comment by tdrozdovsky** [comment]
> 
> 
> > We do delete the opportunity to use other images?
> 
> No. The alpine docker file will not be deleted. We distribute ubuntu image from docker hub, so ubuntu is the official container image at the moment. If any developer who want to use alpine image, he/she can use alpine Dockerfile.

That's right, so I ask how to pass it to build system?

**Comment by t25kim** [comment]
> > > We do delete the opportunity to use other images?
> > 
> > 
> > No. The alpine docker file will not be deleted. We distribute ubuntu image from docker hub, so ubuntu is the official container image at the moment. If any developer who want to use alpine image, he/she can use alpine Dockerfile.
> 
> That's right, so I ask how to pass it to build system?

Are you asking about Alpine?

**Comment by tdrozdovsky** [comment]
> 
> 
> > > > We do delete the opportunity to use other images?
> > > 
> > > 
> > > No. The alpine docker file will not be deleted. We distribute ubuntu image from docker hub, so ubuntu is the official container image at the moment. If any developer who want to use alpine image, he/she can use alpine Dockerfile.
> > 
> > 
> > That's right, so I ask how to pass it to build system?
> 
> Are you asking about Alpine?

yes. I brought all the arguments why **I believe that the build system is left unchanged (while wil not be integrated docker multy stage build). You think otherwise**. For this, I ask which paramaters should be pass to build.

**Comment by t25kim** [comment]
> > > > > We do delete the opportunity to use other images?
> > > > 
> > > > 
> > > > No. The alpine docker file will not be deleted. We distribute ubuntu image from docker hub, so ubuntu is the official container image at the moment. If any developer who want to use alpine image, he/she can use alpine Dockerfile.
> > > 
> > > 
> > > That's right, so I ask how to pass it to build system?
> > 
> > 
> > Are you asking about Alpine?
> 
> yes. I brought all the arguments why **I believe that the build system is left unchanged (while wil not be integrated docker multi-stage build). You think otherwise**. For this, I ask which paramaters should be pass to build.

**We don't maintain the alpine image officially.**

**Comment by t25kim** [comment]
Keep both building instructions.
