### ISSUE TITLE
Tag Version Policy

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#421]
It would be great if we push container images to docker hub frequently whenever any PR is merged.
The general semantic version control policy is as follows: 
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.

However how about increasing the PATCH version when PR (except refactoring and document update) is merged? 
We can deploy container images frequently in this manner.

**Comment by tdrozdovsky** [comment]
I fully agree with @t25kim. Just wanted to offer to do it (I indicated that in the v1.1.1 version were fixed vulnerabilities).
Please **note that all tags must be signed** (`git tag -s v1.1.1`).

**Comment by tdrozdovsky** [comment]
We can also check the correct setting of the requested parameters (DOCKERHUB_USERNAME, DOCKERHUB_PASSWORD).

**Comment by tdrozdovsky** [comment]
I would also like to ask **why was the v2 (2.0.0) label created?**. Since we still do not know whether our version will have _v2.0.0_ or _v1.2.0_? I think that the optimal option is to come up with a name for the next release (for example: Elderberry or other)

**Comment by MoonkiHong** [comment]
@lf-edge/edge-home-orchestration-go-maintainers Recommend to use `v2.0.0` once we fully support all the subordinate components from our Home Edge platform [architecture](https://wiki.lfedge.org/display/HOME/Home+Edge+Platform+Architecture). Before touching that milestone, I would like to recommend to use `v1.2.0` for our next major release. Thought?

**Comment by tdrozdovsky** [comment]
I agree (maybe v2.0.0 if in the next release a condition is performed "MAJOR version when you make incompatible API changes")

**Comment by t25kim** [comment]
> @lf-edge/edge-home-orchestration-go-maintainers Recommend to use `v2.0.0` once we fully support all the subordinate components from our Home Edge platform [architecture](https://wiki.lfedge.org/display/HOME/Home+Edge+Platform+Architecture). Before touching that milestone, I would like to recommend to use `v1.2.0` for our next major release. Thought?

This idea is good. However if we move DataStorage to the another repository(#415), we have to increase Major number due to [API changes](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/api/data_storage_api.yaml). I hope that all subcomponents are implemented in vE.

**Comment by MoonkiHong** [comment]
@tdrozdovsky What about volunteering to release `v1.1.1` for gathering PRs by today? After your initiation, we will refer to your experience. Thoughts? 🙏

**Comment by suresh-lc** [comment]
I understand the point of major version release when there is API level changes. But as @MoonkiHong had mentioned, when new features are added to make the platform complete, new APi's would be added and hence it would qualify as major release. Till then we can have our sub versions. 
How about listing what all components we plan to have as part of vE.

**Comment by tdrozdovsky** [comment]
> @tdrozdovsky What about volunteering to release `v1.1.1` for gathering PRs by today? After your initiation, we will refer to your experience. Thoughts? 🙏

Yes, I'll do it. But it would be good in order to include PR #424 in this tag.

**Comment by t25kim** [comment]
1. Release Home Edge v2 if it fully supports all the subordinate components.
2. Increase MINOR number in the official release before v2.
3. Increase PATCH number and push the tags frequently.

**Comment by MoonkiHong** [comment]
@lf-edge/edge-home-orchestration-go-maintainers From now on, I will create a tag in a weekly basis with the regarding commit (versioning update) every Friday if we have PR(s) in that week.
