### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#425]
For the monitoring purpose, it must be good to have a web UI, such as [edgex foundry](https://github.com/edgexfoundry/edgex-ui-go#use-and-purpose) and [onos-gui](https://wiki.onosproject.org/display/ONOS/Web+UI+Tutorial+-+Creating+a+Topology+Overlay#WebUITutorialCreatingaTopologyOverlay-Overview).

The web UI can display the following items:
- Resource status
- List of service applications installed on the device
- List of devices in the home edge network

**Comment by tdrozdovsky** [comment]
This is a great idea!

**Comment by suresh-lc** [comment]
Nice thought to kick off. This will help in bringing a complete flow of use case and visualize of the same.

**Comment by nitu-s-gupta** [comment]
The idea seems to be great! But I m confused regarding its usability when we say that home edge devices will be low end devices so screen to make this UI helpful is matter of thought for me. Could you please suggest some usecase scenario for its usability
