### ISSUE TITLE
Automatic labeling for PRs

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#432]
**Is your feature request related to a problem? Please describe.**
Many projects use automatic analysis of changes in PRs and set appropriate labels.

**Describe the solution you'd like**
I tried to apply this in our project #428 , but unfortunately the use of a GITHUB_TOKEN for PRs from fork is allowed only with a [read permission](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) .

I propose to consider the [Boring-cyborg](https://github.com/apps/boring-cyborg) option. It allows you to do this and has flexible settings.

Please let me know what you think about this?

**Comment by t25kim** [comment]
It seems like a good idea for convenience!
