### ISSUE TITLE
[Refactoring] Security in main.go

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#441]
> Taking a closer look at main.go I could find isSecured := false if len(secure) > 0 { if strings.Compare(strings.ToLower(secure), "true") == 0 { log.Println("Orchestration init with secure option") isSecured = true } }
> 
> ```
> cipher := dummy.GetCipher(cipherKeyFilePath)
> if isSecured {
> 	verifier.Init(containerWhiteListPath)
> 	authenticator.Init(passPhraseJWTPath)
> 	authorizer.Init(rbacRulePath)
> 	cipher = sha256.GetCipher(cipherKeyFilePath)
> }
> ```
> 
> seems this initiation also need to be moved? 

@tdrozdovsky What do you think about moving this code to securemgr and orchestrationapi? I think we can talk about the securemgr refactoring.

_Originally posted by @t25kim in https://github.com/lf-edge/edge-home-orchestration-go/pull/436#discussion_r769258386_

**Comment by t25kim** [comment]
@tdrozdovsky I think security initiation code in main.go can be moved to `internal/controller/securemgr/securemgr.go`. What do you think?

**Comment by tdrozdovsky** [comment]
> @tdrozdovsky I think security initiation code in main.go can be moved to `internal/controller/securemgr/securemgr.go`. What do you think?

I agree
