### ISSUE TITLE
[Cloud Sync] MQTT TLS Password storage

### ISSUE THREAD

**Issue by suresh-lc** [lf-edge/edge-home-orchestration-go#471]
**Describe the bug**
The MQTT cloud sync can be run in secure mode by enabling the TLS. The method to pass password to CloudSync needs to be defined. Would like to get the opinion of other developers on the same.

**Expected behavior**
Secure method for the password to reach mqttconfig.

**Test environment configuration (please complete the following information):**
* Firmware version: (OS type and version, e.g., Ubuntu 14.04, etc.)
* Hardware: (e.g., x86-64, ARM, CPU type, RAM size, etc.)
* Toolchain: (e.g., Docker and Go versions)
* Edge Orchestration Release: (e.g., Alpha, Baobab, Coconut)

**Additional context**

**Comment by t25kim** [comment]
@tdrozdovsky What if we save cert, username and password to [boltdb](https://pkg.go.dev/go.etcd.io/bbolt)? Is it good?

**Comment by tdrozdovsky** [comment]
Passwords must be stored in encrypted form or as a hash. The certificate contains no sensitive information.
Therefore, storing passwords in an open database is prohibited.

**Comment by t25kim** [comment]
@tdrozdovsky Is sending the result of [mosquitto_passwd](https://mosquitto.org/man/mosquitto_passwd-1.html) through REST API with HTTPS also a problem?

**Comment by nitu-s-gupta** [comment]
https://mosquitto.org/documentation/authentication-methods/
are the methods provided by mosquitto broker

**Comment by t25kim** [comment]
What about the scenario below? 
The service application uses edge-orchestration to the broker when the broker doesn't need Username and Password. 
In other case, the service application should access the broker directly without edge-orchestration.

**Comment by nitu-s-gupta** [comment]
How about creating a textfile for storing password in location /var/edge-orhestration/data folder and then access this file from the code from the Cloudsync mgr package. Please provide your suggestions for the same so that i can raise a PR for it

**Comment by suresh-lc** [comment]
Below article has discussed major methods for securing, thought of sharing the same.
https://www.vaadata.com/blog/how-to-securely-store-passwords-in-database/

Salt and Pepper combined with other methods seems to be widely used for storing the password into Db.
