### ISSUE TITLE
[Security] Need to check: Symlink attack in Libcontainer and Docker Engine

### ISSUE THREAD

**Issue by MoonkiHong** [lf-edge/edge-home-orchestration-go#477]
- Originally reported by: [Link](https://deps.dev/advisory/GHSA/GHSA-g7v2-2qxx-wjrw)
- Our baseline docker engine: https://github.com/lf-edge/edge-home-orchestration-go/blob/f15ac3eddb626d38edffac04ecdbb843eacb1803/go.mod#L13

Need to evaluate if this is a false positive. @tdrozdovsky

**Comment by tdrozdovsky** [comment]
@MoonkiHong Yes you are right, we can ignore this as we are using the `github.com/docker/docker v17.12.0`.
In our repository, I set up a notification system for finding such vulnerabilities that require updating 3-rd party components. 

This issue can be closed!

**Comment by MoonkiHong** [comment]
Thank you @tdrozdovsky 👍
