### ISSUE TITLE
Deleting branches

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#481]
**I strongly suggest deleting the branches: _Baobab, Coconut, dewberries_**

![image](https://user-images.githubusercontent.com/45031429/154334023-d842d615-208c-436f-9956-c9f2aad41835.png)

Reasons:
1) **main reason: one of the OpenSSF Best Practices "gold" badge requirements: _"The project MUST have FLOSS automated test suite(s) that provide at least 80% branch coverage"._ Writing tests for old branches at the moment makes no sense and resources**
2) OpenSSF Score Card requirement for branch protection (needs to be additionally configured) #480
3) We still haven't maintained branches (bug fixes, haven't received external requests for any branches)
4) Now we use a linear development strategy
5) Branches proposed for deletion are associated with tags

I hope we will increase the test coverage of the current code to 90%, and in the future, if necessary, we will be able to use branches for version support (considering that the maturity of our product is growing) 

I hope for a positive result. I can delete myself.

**Comment by tdrozdovsky** [comment]
+1

**Comment by t25kim** [comment]
I second this proposal since developers can find tags related to release.

**Comment by MoonkiHong** [comment]
@tdrozdovsky What about the docker image distributed from DockerHub? Removing it as well? Hope that helps me cast my vote here. 🙏

**Comment by tdrozdovsky** [comment]
> @tdrozdovsky What about the docker image distributed from DockerHub? Removing it as well? Hope that helps me cast my vote here. 🙏

Deleting branches does not affect DockerHub

**Comment by MoonkiHong** [comment]
> > @tdrozdovsky What about the docker image distributed from DockerHub? Removing it as well? Hope that helps me cast my vote here. 🙏
> 
> Deleting branches does not affect DockerHub

@tdrozdovsky My question is - do we need to also delete the docker images of the previous releases from DockerHub? Thank you in advance. 😁

**Comment by tdrozdovsky** [comment]
Since the Docker images are associated with [tags](https://hub.docker.com/r/lfedge/edge-home-orchestration-go/tags) (semantic versions), nothing needs to be deleted. Therefore, I wrote that there will be no impact on the Dockerhub

**Comment by MoonkiHong** [comment]
+1
