### ISSUE TITLE
TestGetDeivceList invoked pending

### ISSUE THREAD

**Issue by ChaJiWon** [lf-edge/edge-home-orchestration-go#5]
=== RUN TestDeviceDetectionRoutine/Success/SuccessNewDevice
--- FAIL: TestDeviceDetectionRoutine (4.00s)
--- FAIL: TestDeviceDetectionRoutine/Success (4.00s)
--- PASS: TestDeviceDetectionRoutine/Success/SuccessClearMap (1.00s)
--- PASS: TestDeviceDetectionRoutine/Success/SuccessDeleteDevice (1.00s)
--- FAIL: TestDeviceDetectionRoutine/Success/SuccessUpdateInfo (1.00s)
discovery_test.go:189: Info Not Updated :: [1.1.1.1]
--- FAIL: TestDeviceDetectionRoutine/Success/SuccessNewDevice (1.00s)
discovery_test.go:197: Device Not Generated
=== RUN TestGetDeviceList
SIGQUIT: quit
PC=0x45d0f1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x80b428, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffa3220028, 0x40b001, ...)
/usr/local/go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x80b428, 0x0, 0xffffffffffffffff)
/usr/local/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x80b428)
/usr/local/go/src/runtime/lock_futex.go:151 +0xa1
runtime.stopm()
/usr/local/go/src/runtime/proc.go:1936 +0xc1
runtime.findrunnable(0xc00002ca00, 0x0)
/usr/local/go/src/runtime/proc.go:2399 +0x54a
runtime.schedule()
/usr/local/go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc000001800)
/usr/local/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x0)
/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000138100, 0x650af5, 0x11, 0x65ab48, 0x474400)
/usr/local/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0000dc000)
/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0000dc000, 0xc0000abdf8)
/usr/local/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00000e2c0, 0x806b80, 0x11, 0x11, 0x0)
/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0000da000, 0x0)
/usr/local/go/src/testing/testing.go:1072 +0x162
main.main()
_testmain.go:126 +0x1cb

goroutine 36 [semacquire]:
sync.runtime_SemacquireMutex(0x80aa1c, 0x7f2df2200d00)
/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x80aa18)
/usr/local/go/src/sync/mutex.go:134 +0x109
controller/discoverymgr.newDeviceHandler(0x656462, 0x22, 0xc000150000)
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery.go:520 +0x3b
controller/discoverymgr.addDevice(0xc000044f01)
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery_test.go:84 +0x1c0
controller/discoverymgr.TestGetDeviceList(0xc000138100)
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery_test.go:209 +0x35
testing.tRunner(0xc000138100, 0x65ab48)
/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 10 [semacquire]:
sync.runtime_SemacquireMutex(0x80aa1c, 0x7f2df2200000)
/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x80aa18)
/usr/local/go/src/sync/mutex.go:134 +0x109
controller/discoverymgr.updateInfoHandler(0x656462, 0x22, 0xc0000b4190)
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery.go:503 +0x3b
controller/discoverymgr.deviceDetectionRoutine.func1(0xc000102000)
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery.go:406 +0x338
created by controller/discoverymgr.deviceDetectionRoutine
/home/wonny/worksapce/for_test/src/controller/discoverymgr/discovery.go:386 +0xec

**Comment by jyong2kim** [comment]
@ChaJiWon 
Please check to this issue is resolved.
If it is resolved, please close this issue.

**Comment by ChaJiWon** [comment]
It is resolved with #6.
