### ISSUE TITLE
GET score API uses request-body to send Orch ID

### ISSUE THREAD

**Issue by suresh-lc** [lf-edge/edge-home-orchestration-go#609]
**Describe the bug**
The Get Score API as below 
/api/v1/scoringmgr/score
take "Orch ID" in request body to return the score.

**To Reproduce**
1. Launch HE in Linux device
2. Call the GET score API
3. The API needs ID in the request body 

**Expected behavior**
GET requests should not typically have request body and request param are used to send data in GET request.

https://stackoverflow.com/questions/58026072/how-to-send-request-body-in-get-method-retrofit

In other words, any HTTP request message is allowed to contain a message body, and thus must parse messages with that in mind. Server semantics for GET, however, are restricted such that a body, if any, has no semantic meaning to the request. ... Yes, you can send a request body with GET but it should not have any meaning.*

**Screenshots**

**Test environment configuration (please complete the following information):**
* Firmware version: Ubuntu 
* Hardware: x86-64, 
* Toolchain: Docker
* Edge Orchestration Release: vD

**Comment by t25kim** [comment]
Thanks for raising  this issue up. 
Do you have any ideas to address this issue?

**Comment by suresh-lc** [comment]
Ya sure trying to make the GET with request-param. @nitu-s-gupta is working on the same.

**Comment by suresh-lc** [comment]
Implemented
