### ISSUE TITLE
Parent Docker Image

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#612]
- The ubuntu 18.04 is deprecated. What about excluding the version from CI?
_The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002_

- The ubuntu [20.04](https://hub.docker.com/_/ubuntu/tags?page=1&name=focal), [22.04](https://hub.docker.com/_/ubuntu/tags?page=1&name=jammy) in docker hub doesn't have `linux/386` platform. What about excluding `linux/386` from the support platform?

- We may include the ubuntu 22.04 to CI.

**Comment by tdrozdovsky** [comment]
I will do it soon! Thank you!
