### ISSUE TITLE
LFHome Edge Colloboration discussion LFHomeEdge Project EVE

### ISSUE THREAD

**Issue by Karthikeyan-Samsung** [lf-edge/edge-home-orchestration-go#72]
**Project EVE:**
LF Home Edge uses Hypervisor II container deployment on the existing OS. No VM/Guest OS required.
Container deployment docker.
But based on the study for cross demonstration with Project EVE, it was identified that the current EVE provides Hypervisor I support. Requesting relevant technical team to provide support for Hypervisor II.

Refered links:
1. https://www.lfedge.org/projects/eve/
2. https://github.com/lf-edge/eve

**Comment by MoonkiHong** [comment]
@Karthikeyan-Samsung Could you post up the material about the EVE collaboration that was presented during the December Home Edge TSC call yesterday? :)

**Comment by suresh-lc** [comment]
![image](https://user-images.githubusercontent.com/52483064/70119261-de10d180-168f-11ea-95a0-9eb9db7620ce.png)
![image](https://user-images.githubusercontent.com/52483064/70119285-eec14780-168f-11ea-93ef-ce27c5d6b72a.png)

**Comment by suresh-lc** [comment]
Eve provides Hypervisor-1 type and Home edge requires Hypervisor-2 type runtime environment. And hence we are identifying few other candidates.
