### ISSUE TITLE
Balena colloboration with LF Home Edge

### ISSUE THREAD

**Issue by Karthikeyan-Samsung** [lf-edge/edge-home-orchestration-go#73]
**Balena:**
Constraint: Balena OS should be preinstalled to use the Container Service.

OpenBalena is a stack of services which offer a combined service to manage balenaOS devices, like Raspberry Pi, Intel NUC etc. It is in no way a hypervisor or offering any kind of virtualization layers.
The issue observed how do Linux will be supported since LF Home Edge runs over Linux. 
From the cloud side looks like there will be dependency on baleana cloud.

**Comment by MoonkiHong** [comment]
@Karthikeyan-Samsung  Could you post up the material about the Balena collaboration (Balena Runtime Engine that should be run on top of Balena OS, which is currently the hurdle for the further collaboration) that was presented during the December Home Edge TSC call yesterday? :)

**Comment by suresh-lc** [comment]
Current understanding of Balena:
Code is submitted to the git server (Balena Platform)
Builders build the docker image
Docker images stored in our container registry,
The device supervisor (Balena OS) manages the pull and push of images 

ISSUES:
Devices need to have Balena OS for using the Balena runtime. Tight dependency on Balena OS

Home-Edge supports devices with Linux OS

**Comment by suresh-lc** [comment]
We are dropping the collaboration with Balena. Balena requires proprietary cloud and OS, which is not feasible in Home Edge environment.
