### ISSUE TITLE
LF Home Edge colloboration with EdgeX foundry

### ISSUE THREAD

**Issue by Karthikeyan-Samsung** [lf-edge/edge-home-orchestration-go#74]
**Edge X foundry:**

Migration from java to Go code will be very helpful for Home Edge since LFHomeEdge is Go language based framework.
EdgeXfoundry planned to migrate the database from Mongo DB to Bolt DB (LF  Home Edge uses Bolt DB).
Its great opportunity for LF Home Edge to closely work for bringing the data storage module from EdgeXFoundry to LF Home Edge.

Collaboration initiated with the conference call(Dec-4)9.30PM MAST with JimWhite(EdgexFoundry CoFounder).

**Comment by MoonkiHong** [comment]
@Karthikeyan-Samsung Could you post up the material about the EdgeX Foundry collaboration (comparison table) that was presented during the December Home Edge TSC call yesterday? :)

**Comment by suresh-lc** [comment]
> @Karthikeyan-Samsung Could you post up the material about the EdgeX Foundry collaboration (comparison table) that was presented during the December Home Edge TSC call yesterday? :)


Our   Understanding for EdgeX | Requirement for   Home Edge
-- | --
Uses MongoDB for data storage | Uses   Bolt Db for data storage
Core-Metadata   stored device info | No master-slave   concept
Core-data   stores sensor data | All devices connected   peer to peer
Has   master-slave concept | Minimal data is   stored at the devices
Core-command   facilitates and controls actuation requests | Data cannot be shared   between the devices
Device service   interacts with actual device | Model can be shared
Export Service   transport data to cloud | Metadata needs to be   aligned to the model

**Comment by MoonkiHong** [comment]
@suresh-lc  Thank you Suresh!

**Comment by suresh-lc** [comment]
We are working with EdgeX for Data Storage and hence closing this.
