### ISSUE TITLE
Edge Orchestrator container fails to shutdown gracefully

### ISSUE THREAD

**Issue by omoliavko** [lf-edge/edge-home-orchestration-go#77]
After Edge Orchestrator container is stopped by 'docker stop edge-orchestrator' command, Edge Orchestrator remains active, listening to port 56002; this causes any further attempt to restart container to fail. Current workaround is manually killing process and cleaning db folder.
[log.txt](https://github.com/lf-edge/edge-home-orchestration-go/files/3955538/log.txt)

**Comment by MoonkiHong** [comment]
@tdrozdovsky Makes sense. Thank you for your kind confirmation.
