### ISSUE TITLE
Need to add popular platforms (for ex. Raspberry Pi x)

### ISSUE THREAD

**Issue by tdrozdovsky** [lf-edge/edge-home-orchestration-go#79]
**Is your feature request related to a problem? Please describe.**
Lack of supported platforms other than x86_64

**Describe the solution you'd like**
It would be nice to add popular platforms like as _Raspberry Pi x_ to attract more developers.

**Describe alternatives you've considered**

**Additional context**
Any platform on which Linux can be run is suitable for this.

**Comment by MoonkiHong** [comment]
@suresh-lc Please let us know if this issue can be closed once the regarding PR #80 is approved and merged.
