### ISSUE TITLE
OrchestrationInit() failed for java binding / c binding due to recent security changes

### ISSUE THREAD

**Issue by jay11ca39** [lf-edge/edge-home-orchestration-go#93]
**Describe the bug**
Due to recent changes https://github.com/lf-edge/edge-home-orchestration-go/pull/90/files which mandate verifier to be enabled for all the platforms: Container, native and android. It makes orchestrationInit() API to be failed for interfaces (src/interfaces/javaapi and src/interfaces/capi) 

**To Reproduce**
1. Generate java object.
2. Include binding in application. 
3. Call orchestrationInit() API.  **(It is failing)**

**Expected behavior**
OrchestrationInit() should work for all the platform.

**Suggestion**
File Name: orchestration.go 
Line No: 162 (!o.isSetVerifierConf )

The above check should be done only for container platform. As this is common file for all the platform. 
Please check the common files for different platform and put necessary conditional checks.

**Comment by jay11ca39** [comment]
@tdrozdovsky 
Can you provide your opinion on this ?

**Comment by tdrozdovsky** [comment]
I am very glad that you are also interested in the operability of the orchestration in a secure mode. Initially, I could not find a description or an example of how to run under other platforms and therefore did not add code for these platforms. Now I have added it. If you have any information about these platforms, please share with me. I hope together we will make the edge-orchestration more secure
